#!/bin/bash
# names = lspc_tmhrhr, ntta, lspd_n0
# curr = 17,28,35
nam="lspc_tmhrhr"
run=20
prevrun=$(($run-1))
state=0

if [ $state == 0 ]; then
	scp -r ~/data/nmr/${nam}/ccpnmr/run${run}analysis/ tportlock@tportlock.nmrbox.org:/home/nmrbox/tportlock/aria/${nam}/ &&
	ssh tportlock@tportlock.nmrbox.org "cd aria/$nam && cp run${prevrun}.xml run$run.xml && mv run$prevrun.xml run${prevrun}analysis run$prevrun.log run$prevrun && sed -i 's/run${prevrun}/run${run}/g' run${run}.xml && sed -i 's/\"${prevrun}\"\ file_root/\"${run}\"\ file_root/g' run$run.xml && sed -i 's/run${prevrun}analysis/run${run}analysis/g' run${run}.xml"
	# && aria2 -s run${run}.xml ; aria2 --output=run${run}.log run${run}.xml > /dev/null 2>&1 &" &&
fi

if [ $state = 1 ]; then
	scp -r tportlock@tportlock.nmrbox.org:"/home/nmrbox/tportlock/aria/${nam}/run${run}/structures/it8 /home/nmrbox/tportlock/aria/${nam}/run${run}/structures/refine /home/nmrbox/tportlock/aria/${nam}/run${run}analysis" .
	mv run${run}analysis run${run}analysisR;
	mv run${run}analysisR ~/data/nmr/${nam}/ccpnmr/;
	mv it8 run${run}structures;
	mv run${run}structures ~/data/nmr/${nam}/ariastructures;
	mv refine run${run}refinestructures;
	mv run${run}refinestructures ~/data/nmr/${nam}/ariastructures;
fi

