#!/bin/csh 
var2pipe -in ./y2at_hqtoc.var   \ 
  -xN             1024   \ 
  -yN              256   \ 
  -zN               64   \ 
  -xT              512   \ 
  -yT              128   \ 
  -zT               32   \ 
  -xMODE        Complex  \ 
  -yMODE        Complex  \ 
  -zMODE      Rance-Kay  \ 
  -xSW         6200.000  \ 
  -ySW         6200.000  \ 
  -zSW         1650.000  \ 
  -xOBS         500.297  \ 
  -yOBS         500.297  \ 
  -zOBS          50.700  \ 
  -xCAR           4.914  \ 
  -yCAR           4.914  \ 
  -zCAR         118.700  \ 
  -xLAB              H1  \ 
  -yLAB              H1  \ 
  -zLAB             N15  \ 
  -ndim               3  \ 
  -aqORD              1  \ 
  -out ./temp_files/test%03d.fid -verb -ov 
# 
xyz2pipe -in temp_files/test%03d.fid -x -verb  \ 
  | nmrPipe -fn SP -off 0.36 -end 0.998 -pow 1 -c 1.0  \ 
  | nmrPipe -fn ZF -auto      \ 
  | nmrPipe -fn FT          \ 
  | nmrPipe -fn PS -p0 -104.0 -p1 0.0      \ 
  | nmrPipe -fn EXT -x1 11.24ppm -xn 5.6ppm -sw -round  \ 
  | pipe2xyz -out temp_files/test%03d.ft1 -x        \ 
# 
xyz2pipe -in temp_files/test%03d.ft1 -z -verb  \ 
  | nmrPipe -fn SP -off 0.36 -end 0.99 -pow 1 -c 0.6         \ 
  | nmrPipe -fn ZF -auto    \ 
  | nmrPipe -fn FT    \ 
  | nmrPipe -fn PS -p0 0.0 -p1 0.0  -di         \ 
  | nmrPipe -fn REV       \ 
  | pipe2xyz -out temp_files/test%03d.ft2 -z -verb    \ 
# 
xyz2pipe -in temp_files/test%03d.ft2 -y -verb   \ 
  | nmrPipe -fn SP -off 0.36 -end 0.99 -pow 1 -c 0.6        \ 
  | nmrPipe -fn ZF -auto    \ 
  | nmrPipe -fn FT      \ 
  | nmrPipe -fn PS -p0 0.0 -p1 0.0  -di   \ 
  | nmrPipe -fn POLY -auto   \ 
  | pipe2xyz -out temp_files/test%3d.ft3 -y -verb   \ 
# 
xyz2pipe -in temp_files/test%3d.ft3 -x -verb   \ 
  | nmrPipe -fn POLY -auto     \ 
  | pipe2xyz -out temp_files/test%3d.ft4 -x -verb   \ 
# 
xyz2pipe -in temp_files/test%3d.ft4 -z -out spectrum  \ 
# 
pipe2ucsf spectrum y2at_hqtoc.spa 
cp y2at_hqtoc.spa ~/Sparky/Save/ 
# 
rm -rf temp_files 
rm -f spectrum 
#
