#!/bin/csh 
var2pipe -in ./y2a_hcch.var   \ 
  -xN             1024   \ 
  -yN              256   \ 
  -zN               92   \ 
  -xT              512   \ 
  -yT              256   \ 
  -zT               92   \ 
  -xMODE        Complex  \ 
  -yMODE           Real  \ 
  -zMODE           Real  \ 
  -xSW         5800.000  \ 
  -ySW         5800.000  \ 
  -zSW         8400.000  \ 
  -xOBS         500.297  \ 
  -yOBS         500.297  \ 
  -zOBS         125.800  \ 
  -xCAR           4.914  \ 
  -yCAR           4.914  \ 
  -zCAR           43.10  \ 
  -xLAB              H1  \ 
  -yLAB              H1  \ 
  -zLAB             C13  \ 
  -ndim               3  \ 
  -out ./temp_files/test%03d.fid -verb -ov 
xyz2pipe -in temp_files/test%03d.fid -x -verb  \ 
  | nmrPipe -fn SP -off 0.36 -end 0.99 -pow 1 -c 1.0         \ 
# | nmrPipe -fn EM -lb 20.0      \ 
  | nmrPipe -fn ZF -auto      \ 
  | nmrPipe -fn FT          \ 
  | nmrPipe -fn PS -p0 146.0 -p1 0.0 -di         \ 
  | nmrPipe -fn EXT -x1 6.0ppm -xn -0.5ppm -sw -round  \ 
  | pipe2xyz -out temp_files/test%03d.ft1 -x        \ 
# 
  xyz2pipe -in temp_files/test%03d.ft1 -y -verb  \ 
  | nmrPipe -fn SP -off 0.36 -end 0.99 -pow 1 -c 1.0         \ 
  | nmrPipe -fn ZF -auto    \ 
  | nmrPipe -fn FT -real   \ 
  | nmrPipe -fn PS -p0 0.0  -p1 0.0  -di         \ 
  | nmrPipe -fn REV                             \ 
  | pipe2xyz -out temp_files/test%03d.ft2 -y -verb    \ 
# 
  xyz2pipe -in temp_files/test%03d.ft2 -z -verb   \ 
  | nmrPipe -fn SP -off 0.36 -end 0.99 -pow 1 -c 1.0        \ 
  | nmrPipe -fn ZF -auto    \ 
  | nmrPipe -fn FT -real      \ 
  | nmrPipe -fn PS -p0 0.0 -p1 0.0  -di   \ 
  | nmrPipe -fn REV                       \ 
  | pipe2xyz -out temp_files/test%3d.ft3 -z -verb   \ 
# 
xyz2pipe -in temp_files/test%3d.ft3 -x -verb   \ 
  | nmrPipe -fn POLY -auto     \ 
  | pipe2xyz -out temp_files/test%3d.ft4 -x -verb   \ 
# 
xyz2pipe -in temp_files/test%3d.ft4 -y -verb   \ 
  | nmrPipe -fn POLY -auto     \ 
  | nmrPipe -fn EXT -x1 6.0ppm -xn -0.5ppm -sw -round  \ 
  | pipe2xyz -out temp_files/test%3d.ft5 -y -verb   \ 
# 
xyz2pipe -in temp_files/test%3d.ft5 -z -out spectrum  \ 
# 
pipe2ucsf spectrum y2a_hcch.spa 
cp y2a_hcch.spa ~/Sparky/Save 
# 
rm -rf temp_files 
rm -f spectrum 
#
