#!/usr/bin/env python

import sys
import pandas as pd
import matplotlib.pyplot as plt
import os

df = []

for x in range(len(sys.argv)-1):
    print(x)
    df.append(pd.read_csv(sys.argv[x])
    df[x]["Molar Excess"]=x

fig, ax = plt.subplots(1,1)

x = 'Assign F1'
y = 'Position F1'

#x = list(df)[0]
#y = list(df)[3]

for i in df[0][x].index:
        ax.scatter(i, df[i][y]-df[0][y])

#ax.set(ylabel=y) 
#plt.xticks(rotation=90)
#plt.xlabel(x)
#plt.tight_layout()
#plt.savefig("output.svg")
'''
