#!/usr/bin/env python

import sys
import pandas as pd
import matplotlib.pyplot as plt
import os

df = pd.read_csv(sys.argv[1])

fig, ax = plt.subplots(1,1)

x = list(df)[0]
y = list(df)[3]

ax.bar(df[x], df[y])
ax.set(ylabel=y) 
plt.xticks(rotation=90)
plt.xlabel(x)
plt.tight_layout()
plt.savefig(os.path.splitext(sys.argv[1])[0]+".svg")
